package main

import "net/http"

// The manifest is the substrate describing itself to agents. An agent that
// fetches /.well-known/waggle.json learns every action, its verbs, parameters
// and semantics — no human documentation required in the loop. This is the
// agent-native equivalent of a landing page.
func (s *Server) handleManifest(w http.ResponseWriter, r *http.Request) {
	resources, signals := s.field.Stats()
	writeJSON(w, http.StatusOK, map[string]any{
		"protocol":    "waggle/v1",
		"service":     "Waggle stigmergic coordination substrate",
		"description": "Indirect coordination for agent swarms: deposit decaying signals on resources, sniff before acting, follow gradients, claim leases, broadcast dances, and persist namespaced memory. Signals evaporate — stale knowledge fades automatically.",
		"live": map[string]any{
			"agents": len(s.agents.List()), "resources": resources, "signals": signals,
		},
		"signal_kinds":   WellKnownKinds,
		"channels":       s.field.channels.List(),
		"evidence_tiers": EvidenceTiers,
		"conventions": []string{
			"Resources are arbitrary URIs: file paths (repo://src/main.go), URLs, topics (topic://auth-refactor), tasks (task://issue-42).",
			"Sniff before you act: check for dead-end and claimed signals to avoid repeating the swarm's mistakes.",
			"Mark after you act: deposit explored/gold/dead-end so successors inherit your experience.",
			"Reinforce what matters: re-depositing the same kind on the same resource strengthens the trail and resets its decay.",
			"Claim before exclusive work; leases expire, so a crashed agent never wedges a resource.",
			"Dance only for swarm-wide news; ambient knowledge belongs in signals.",
		},
		"actions": []map[string]any{
			{"name": "register", "method": "POST", "path": "/v1/agents",
				"params": map[string]string{"id": "optional stable id (resuming keeps memory namespace)", "name": "display name", "goals": "[]string", "skills": "[]string"},
				"doc":    "Create or resume an agent profile. Returns the profile including memory_namespace."},
			{"name": "deposit", "method": "POST", "path": "/v1/signals",
				"params": map[string]string{"agent": "required", "resource": "required URI", "kind": "required (see signal_kinds)", "intensity": "0-10, default 1", "half_life_s": "decay half-life seconds, default 1800", "decay": "'exp' (default) or 'power' — heavy tail: halves at one half-life but fades to background instead of nothing; use for durable findings", "alpha": "power-law exponent, default 1 (higher = faster tail)", "note": "free text for successors", "meta": "map[string]string"},
				"doc":    "Deposit a decaying scent mark. Same agent+resource+kind reinforces the existing signal."},
			{"name": "sniff", "method": "GET", "path": "/v1/sniff",
				"params": map[string]string{"resource": "exact URI", "prefix": "URI prefix", "kind": "filter", "agent": "filter", "min": "min intensity", "min_tier": "minimum evidence tier (e.g. corroborated filters out self-reports)", "limit": "max results"},
				"doc":    "Read current (decayed) signals, strongest first. Each carries effective_intensity: decay x evidence-tier weight x cross-inhibition."},
			{"name": "gradient", "method": "GET", "path": "/v1/gradient",
				"params": map[string]string{"prefix": "URI prefix", "kind": "filter", "k": "top-k, default 20", "depth": "roll signals up to this level of the URI tree (0=scheme, 1=first segment, ...); omit for individual resources. Orient coarse-to-fine: depth=1, descend into the hottest subtree, repeat", "weighted": "true = trust-adjusted totals (evidence-tier weight x cross-inhibition)", "diffuse": "true = 5% sibling bleed at leaf level: hot neighborhoods warm unmarked resources"},
				"doc":    "Ranked hotspots: where is the swarm's attention? Filter kind=help for a rescue map, kind=gold for a findings map. With depth, a self-similar zoomable map of the whole tree."},
			{"name": "claim", "method": "POST", "path": "/v1/claims",
				"params": map[string]string{"agent": "required", "resource": "required", "ttl_s": "lease seconds, default 300"},
				"doc":    "Acquire or renew an exclusive lease. 409 with holder if already held."},
			{"name": "release", "method": "POST", "path": "/v1/claims/release",
				"params": map[string]string{"agent": "required", "resource": "required"},
				"doc":    "Release a held lease."},
			{"name": "claims", "method": "GET", "path": "/v1/claims", "doc": "List live leases."},
			{"name": "dance", "method": "POST", "path": "/v1/dances",
				"params": map[string]string{"agent": "required", "topic": "required", "payload": "arbitrary JSON"},
				"doc":    "Broadcast to the whole swarm (bee waggle dance)."},
			{"name": "dances", "method": "GET", "path": "/v1/dances",
				"params": map[string]string{"since": "sequence cursor", "topic": "filter", "limit": "max"},
				"doc":    "Poll broadcasts after a sequence cursor."},
			{"name": "memory_put", "method": "PUT", "path": "/v1/memory/{namespace}/{key}",
				"doc": "Store any JSON value in a namespace. Agents own their profile namespace; shared namespaces are by convention."},
			{"name": "memory_get", "method": "GET", "path": "/v1/memory/{namespace}/{key}",
				"doc": "Fetch a stored value. GET /v1/memory/{namespace}?keys=1 lists keys."},
			{"name": "sniff_batch", "method": "POST", "path": "/v1/sniff/batch",
				"params": map[string]string{"uris": "[]string (max 256), each treated as a subtree prefix", "kind": "filter", "weighted": "true = effective intensities (tier weight x cross-inhibition)"},
				"doc":    "Gradient rollups for many URIs in one call — price N candidate branches for one round-trip."},
			{"name": "sniff_explain", "method": "GET", "path": "/v1/explain",
				"params": map[string]string{"resource": "required exact URI"},
				"doc":    "Why does this resource read the way it does: every live signal with its evidence tier, tier weight, the cross-inhibitions suppressing it, effective intensity, and the ambient diffusion from siblings."},
			{"name": "recall", "method": "GET", "path": "/v1/recall",
				"params": map[string]string{"at": "required RFC3339 instant", "resource": "exact URI", "prefix": "URI prefix", "kind": "filter", "agent": "filter", "min": "min intensity at the instant", "limit": "max results"},
				"doc":    "Historical field state: replays the journal to the instant and returns signals decayed to then, not now. Requires persistence (-data). 409 without a journal."},
			{"name": "channels", "method": "GET", "path": "/v1/channels",
				"doc": "List typed channels: decay defaults, reinforcement semantics (add/replace), cross-inhibitions, and the evidence-tier ladder."},
			{"name": "channel_register", "method": "POST", "path": "/v1/channels",
				"params": map[string]string{"name": "required", "doc": "description", "default_half_life_s": "deposit default", "decay_kernel": "'exp' or 'power'", "default_alpha": "power exponent", "alpha_from_value": "bool: alpha = alpha_max - (alpha_max-alpha_min)*intensity/10", "reinforce": "'add' (default) or 'replace' (verdict semantics)", "cross_inhibits": "[{channel, mode: 'high'|'low', ref, floor}]"},
				"doc":    "Self-register a typed channel — how a new power teaches the substrate its signal type without a source change."},
			{"name": "watch_register", "method": "POST", "path": "/v1/watches",
				"params": map[string]string{"agent": "required depositor identity", "name": "label", "resource_prefix": "prepended to incoming resources", "map": "outcome->kind, default {success: gold, failure: dead-end}", "evidence_tier": "default watch-derived"},
				"doc":    "Register a derivation rule: state transitions POSTed to the returned ingest_path become deposits at watch-derived trust, no mark calls required."},
			{"name": "watch_ingest", "method": "POST", "path": "/v1/ingest/{id}",
				"params": map[string]string{"resource": "required", "outcome": "translated via the watch's map", "kind": "or named directly", "subtype": "finer label (e.g. compile stage)", "intensity": "0-10", "note": "free text", "meta": "map[string]string"},
				"doc":    "Push one state transition to a watch; the derived signal is deposited and returned."},
			{"name": "territory_set", "method": "POST", "path": "/v1/territories",
				"params": map[string]string{"prefix": "required URI prefix", "tempo": "default half-life multiplier: <1 fast territory, >1 slow"},
				"doc":    "Tune the rhythm of a region: deposits under the prefix that omit half_life_s get the territory's tempo, and claim-velocity evaporation stacks on top (contested territory decays up to 2x faster). Both apply only inside registered territories — unregistered field keeps classic deterministic defaults."},
			{"name": "events", "method": "GET", "path": "/v1/events",
				"doc": "Server-sent event stream of everything happening on the substrate."},
			{"name": "agents", "method": "GET", "path": "/v1/agents", "doc": "List agent profiles, most recently active first."},
			{"name": "status", "method": "GET", "path": "/v1/status", "doc": "Service health and live counts."},
		},
		"clients": map[string]string{
			"cli":    "cli/ — `wag`, a zero-dependency Rust binary for shell-native agents",
			"mcp":    "mcp/waggle_mcp.py — zero-dependency MCP stdio server for MCP-native agents",
			"python": "sdk/python/waggle.py — Python SDK for programmatic swarms",
			"human":  "GET / — the Observatory, a live view of the field (humans are guests here)",
		},
	})
}
